import { expect } from "chai";
import { ethers } from "hardhat";
// Import the type generated by your compilation
import { OmegaLottery } from "../typechain-types";

describe("OmegaLottery", function () {
  let lottery: OmegaLottery;
  let owner: any;
  // In v6, parseEther returns a native BigInt
  const ENTRY_FEE = ethers.parseEther("1.0");

  beforeEach(async function () {
    [owner] = await ethers.getSigners();

    const OmegaLotteryFactory = await ethers.getContractFactory("OmegaLottery");

    // Updated: encodeBytes32String replaces utils.formatBytes32String
    const dummyKeyHash = ethers.encodeBytes32String("keyhash");

    lottery = await OmegaLotteryFactory.deploy(
      1n, // Using 'n' for BigInt
      owner.address,
      dummyKeyHash,
    );
  });

  it("Should create a lottery with correct fee", async function () {
    const start = Math.floor(Date.now() / 1000) + 60;
    const end = start + 3600;

    await lottery.createLottery(ENTRY_FEE, start, end);
    const lotteryObj = await lottery.getLottery(1n);

    // In v6, comparison is direct with BigInt
    expect(lotteryObj.entryFee).to.equal(ENTRY_FEE);
  });
});
